In [1]:
 pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import numpy as np


In [13]:
arr = np.array([1, 2, 3])

In [14]:
arr


array([1, 2, 3])

In [15]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr,arr_2d)

[1 2 3] [[1 2 3]
 [4 5 6]]


In [16]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.arange(0, 5, 2)

array([0, 2, 4])

In [23]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [24]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.random.rand(3, 2)

array([[0.55316826, 0.77069289],
       [0.97507424, 0.32941193],
       [0.14958008, 0.17181603]])

In [26]:
np.random.randn(3, 2)

array([[ 0.19240038, -0.89890778],
       [-0.42573341, -0.79756382],
       [-1.03634309,  1.76039384]])

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [29]:
print(arr.ndim)

2


In [30]:
print(arr.size)

6


In [31]:
print(arr.dtype)

int64


In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [33]:
a * b

array([ 4, 10, 18])

In [34]:
a-b

array([-3, -3, -3])

In [35]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [37]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [39]:
arr = np.array([1, 2, 3, 4])
arr.sum()

np.int64(10)

In [40]:
arr.mean()

np.float64(2.5)

In [41]:
arr.max()

np.int64(4)

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.std()

np.float64(1.118033988749895)

In [44]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]

np.int64(1)

In [45]:
arr[1:4]

array([2, 3, 4])

In [46]:
arr[::2]

array([1, 3, 5])

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]

np.int64(2)

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr[:, 1]

array([2, 5])

In [49]:
arr[1, :2]

array([4, 5])

In [51]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr>3
arr[mask]

array([4, 5])

In [56]:
arr[1:3]

array([[4, 5, 6]])

In [57]:
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [62]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [64]:
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

In [65]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [68]:
# Save to a file
np.save('array.npy',arr)

In [70]:
loaded_arr = np.load('array.npy')